# This is a basic workflow to help you get started with Actions

name: Running CYPRESS with CUCUMBER E2E Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ cucumber ]
  pull_request:
    branches: [ cucumber ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get npm cache
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm cache dir)"
        
      - name: Install dependencies
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Run Cypress Cucumber Scenarios
        uses: cypress-io/github-action@v2
        continue-on-error: true
        if: always()
        with:
          install: false
          record: true
          browser: chrome
        env: 
          CI: true
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #browser: chrome 
        
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cucumberJson
          path: cypress/cucumber-json 
        
