# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ cypressAPI ]
  pull_request:
    branches: [ cypressAPI ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

        #Run mock server
      - name: npm install -g json-server
        run: |
          npm install -g json-server
          npm install i faker
          npm run js:server
        timeout-minutes: 10
