# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ cypressAPI ]
  pull_request:
    branches: [ cypressAPI ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

        #Run mock server
      - name: npm install -g json-server and npm run js:server
        uses: cypress-io/github-action@v1
        timeout-minutes: 10

        #Execute API Tests
      - name: Cypress run with env
        uses: cypress-io/github-action@v1
        if: always()
        with:
          record: true
          browser: chrome
          group: 'Actions example'
        env: 
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #browser: chrome 
          CYPRESS_reqres_url: "https://reqres.in"
          CYPRESS_gorest_url: "https://gorest.co.in"
          CYPRESS_github_url: "https://api.github.com"
          CYPRESS_auth_username: ${{ secrets.AUTH_USERNAME }}
          CYPRESS_auth_password: ${{ secrets.AUTH_PASSWORD }}
          CYPRESS_bearer_token: ${{ secrets.GOREST_TOKEN }}
          CYPRESS_github_bearer_token: ${{ secrets.GTH_TOKEN }}  
        
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
